-- MySQL Script generated by MySQL Workbench
-- Tue Jul  4 13:57:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mtmart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mtmart` ;

-- -----------------------------------------------------
-- Schema mtmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mtmart` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `mtmart` ;

-- -----------------------------------------------------
-- Table `mtmart`.`aparelho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mtmart`.`aparelho` ;

CREATE TABLE IF NOT EXISTS `mtmart`.`aparelho` (
  `IdAparelho` INT NOT NULL AUTO_INCREMENT,
  `Cod` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `DataInstalacao` DATETIME(6) NOT NULL,
  `Biologo` VARCHAR(100) NOT NULL,
  `Numero` INT NOT NULL,
  PRIMARY KEY (`IdAparelho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mtmart`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mtmart`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mtmart`.`cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(14) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mtmart`.`ph`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mtmart`.`ph` ;

CREATE TABLE IF NOT EXISTS `mtmart`.`ph` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `IdAparelho` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Data` DATETIME(6) NOT NULL,
  `Valor` DOUBLE NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `IdAparelho` (`IdAparelho` ASC) VISIBLE,
  CONSTRAINT `ph_ibfk_1`
    FOREIGN KEY (`IdAparelho`)
    REFERENCES `mtmart`.`aparelho` (`IdAparelho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mtmart`.`temperatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mtmart`.`temperatura` ;

CREATE TABLE IF NOT EXISTS `mtmart`.`temperatura` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `IdAparelho` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Data` DATETIME(6) NOT NULL,
  `Valor` DOUBLE NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `IdAparelho` (`IdAparelho` ASC) VISIBLE,
  CONSTRAINT `temperatura_ibfk_1`
    FOREIGN KEY (`IdAparelho`)
    REFERENCES `mtmart`.`aparelho` (`IdAparelho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mtmart`.`turbidez`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mtmart`.`turbidez` ;

CREATE TABLE IF NOT EXISTS `mtmart`.`turbidez` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `IdAparelho` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Data` DATETIME(6) NOT NULL,
  `Valor` DOUBLE NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `IdAparelho` (`IdAparelho` ASC) VISIBLE,
  CONSTRAINT `turbidez_ibfk_1`
    FOREIGN KEY (`IdAparelho`)
    REFERENCES `mtmart`.`aparelho` (`IdAparelho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mtmart`.`viveiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mtmart`.`viveiro` ;

CREATE TABLE IF NOT EXISTS `mtmart`.`viveiro` (
  `IdViveiro` INT NOT NULL AUTO_INCREMENT,
  `NomeViveiro` VARCHAR(100) NOT NULL,
  `AparelhoId` INT NOT NULL,
  `Cliente` INT NOT NULL,
  PRIMARY KEY (`IdViveiro`),
  INDEX `Cliente` (`Cliente` ASC) VISIBLE,
  INDEX `AparelhoId` (`AparelhoId` ASC) VISIBLE,
  CONSTRAINT `viveiro_ibfk_1`
    FOREIGN KEY (`Cliente`)
    REFERENCES `mtmart`.`cliente` (`IdCliente`),
  CONSTRAINT `viveiro_ibfk_2`
    FOREIGN KEY (`AparelhoId`)
    REFERENCES `mtmart`.`aparelho` (`IdAparelho`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
